### ISSUE TITLE
Missing copyright and license information for individual files

### ISSUE THREAD

**Issue by johanvx** [PMR-Fansub/subflow-react#17]
It's almost always nice to add copyright and license information to every single file. One evident reason is that with these kinds of information, once people extract some files from the project, by just reading those files, they can easily find out under which license(s) the files are distributed and to whom the copyright belongs.

I've checked our back-end project and found that that project is GPL-3.0-or-later licensed. I want to know if this project is also GPL-3.0-or-later. Or maybe this project is GPL-3.0-only? Please let me know if not very busy 😝

**Comment by Ginakira** [comment]
What's your recommendation? Actually, I don't know the detailed differences between them.
I hope it's up to you to decide which license we should use.

**Comment by johanvx** [comment]
Well I guess GPL-3.0-or-later would be fine.

The main difference between GPL-3.0-only and GPL-3.0-or-later is that the former specify the GNU General Public License v3.0 while the latter allows to apply the version 3.0 or any newer versions (say 3.1, 3.2 or even 4.0 if these versions are available). I personally think the updates of GPL (if any) won't introduce anything that we don't want to respect. If they do, we can then change our license.

**Comment by Ginakira** [comment]
Okay, It's fine.

**Comment by johanvx** [comment]
Closed by #18 .
