### ISSUE TITLE
A toast should be added after modifying the nickname successfully

### ISSUE THREAD

**Issue by Ginakira** [PMR-Fansub/subflow-react#9]
I think a toast should be added after modifying the nickname successfully. @johanvx 

See: `src/utils/auth.js` Line 95 

https://github.com/PMR-Fansub/subflow-react/blob/edfad6dcbb3f562783d079dab41734cb3eb524ad/src/utils/auth.js#L95

**Comment by johanvx** [comment]
> I think a toast should be added after modifying the nickname successfully. @johanvx 
> 
> 
> 
> See: `src/utils/auth.js` Line 95 
> 
> 
> 
> https://github.com/PMR-Fansub/subflow-react/blob/edfad6dcbb3f562783d079dab41734cb3eb524ad/src/utils/auth.js#L95

Good idea. This would be added soon.
